### ISSUE TITLE
Another ditto error Xcode10.1

### ISSUE THREAD

**Issue by Bretterteig** [facebook/Recipes-for-AutoPkg#22] opened 2019-03-14 15:04 UTC
Error while extracting Xcode10.1 or Xcode10 with XcodeXIPUnpacker.

Error: ditto: cipo read error: bad file format.

Manual extract does work. Tried on multiple machines. Always the same.

**Comment by nmcspadden** [comment] 2019-03-19 18:42
I'm unable to repro this. I downloaded Xcode 10.1.xip from the Apple Dev site, and ran the recipe on it:

```
autopkg run -vvv ./Xcode.munki.recipe -p ~/Downloads/Xcode_10.1.xip
Processing ./Xcode.munki.recipe...
WARNING: ./Xcode.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': u'1.0.5',
 u'CACHE_DIR': u'/Volumes/Repo/Cache',
 u'DESTINATION_APP_NAME': u'Xcode.app',
 u'ICON_NAME': u'Xcode.png',
 u'MUNKI_REPO': u'/Users/nmcspadden/it-bin/shelves/cpe_munki/munki_repo',
 u'MUNKI_REPO_SUBDIR': u'apps/apple/xcode/',
 u'NAME': u'Xcode',
 'PARENT_RECIPES': [u'/Users/nmcspadden/Downloads/fbrecipes/Recipes-for-AutoPkg/Xcode/Xcode.extract.recipe'],
 'PKG': '/Users/nmcspadden/Downloads/Xcode_10.1.xip',
 'RECIPE_CACHE_DIR': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki',
 'RECIPE_DIR': '/Users/nmcspadden/Downloads/fbrecipes/Recipes-for-AutoPkg/Xcode',
 u'RECIPE_OVERRIDE_DIRS': [u'/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/nmcspadden/Downloads/fbrecipes/Recipes-for-AutoPkg/Xcode/Xcode.munki.recipe',
 u'RECIPE_REPOS': {u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.bnpl-recipes': {
    URL = "https://github.com/autopkg/bnpl-recipes";
},
                   u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {
    URL = "https://github.com/autopkg/dataJAR-recipes";
},
                   u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes': {
    URL = "https://github.com/autopkg/mosen-recipes";
},
                   u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {
    URL = "https://github.com/autopkg/recipes";
},
                   u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {
    URL = "https://github.com/autopkg/rtrouton-recipes";
}},
 u'RECIPE_REPO_DIR': u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos',
 u'RECIPE_SEARCH_DIRS': [u'.',
                         u'~/Library/AutoPkg/Recipes',
                         u'/Library/AutoPkg/Recipes',
                         u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                         u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                         u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                         u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.bnpl-recipes',
                         u'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes',
                         '.'],
 u'pkginfo': {
    catalogs =     (
        testing
    );
    description = Xcode;
    "display_name" = Xcode;
    name = Xcode;
    "unattended_install" = 1;
},
 'verbose': 3}
PackageRequired
{'Input': {}}
{'Output': {}}
XcodeXIPUnpacker
{'Input': {'PKG': '/Users/nmcspadden/Downloads/Xcode_10.1.xip'}}
XcodeXIPUnpacker: Xar unpacking /Users/nmcspadden/Downloads/Xcode_10.1.xip
XcodeXIPUnpacker:
XcodeXIPUnpacker: Finished xar unpack.
XcodeXIPUnpacker: Gunzip unpacking /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/xar/Content.part00.cpio.xz
XcodeXIPUnpacker:
XcodeXIPUnpacker: Finished gunzipping.
XcodeXIPUnpacker: Gunzip unpacking /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/xar/Content.part02.cpio.xz
XcodeXIPUnpacker:
XcodeXIPUnpacker: Finished gunzipping.
XcodeXIPUnpacker: Combining .cpio files together
XcodeXIPUnpacker: Ditto extraction of CPIO archive /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Content.cpio
XcodeXIPUnpacker:
XcodeXIPUnpacker: Finished ditto extraction.
XcodeXIPUnpacker: Cleaning up temporary archives.
{'Output': {'output_app': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app'}}
CodeSignatureVerifier
{'Input': {'input_path': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app',
           'requirement': u'identifier "com.apple.dt.Xcode" and anchor apple'}}
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app: valid on disk
CodeSignatureVerifier: /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
PlistReader
{'Input': {'info_path': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app/Contents/version.plist',
           'plist_keys': {
    CFBundleShortVersionString = version;
    CFBundleVersion = bundleversion;
    ProductBuildVersion = productbuildversion;
}}}
PlistReader: Reading: /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app/Contents/version.plist
PlistReader: Assigning value of '10.1' to output variable 'version'
PlistReader: Assigning value of '10B61' to output variable 'productbuildversion'
PlistReader: Assigning value of '14460.46' to output variable 'bundleversion'
{'Output': {'plist_reader_output_variables': {u'bundleversion': u'14460.46',
                                              u'productbuildversion': u'10B61',
                                              u'version': u'10.1'}}}
XcodeVersioner
{'Input': {'version': u'10.1'}}
XcodeVersioner: Major version: 10
XcodeVersioner: Minor version: 1
XcodeVersioner: Normalizing patch to 0
XcodeVersioner: Patch version: 0
{'Output': {'major_version': '10', 'minor_version': '1', 'patch_version': '0'}}
PkgRootCreator
{'Input': {'pkgdirs': {
    Applications = 0755;
},
           'pkgroot': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode'}}
PkgRootCreator: Created /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode
PkgRootCreator: Creating Applications
PkgRootCreator: Created /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode/Applications
{'Output': {}}
FileMover
{'Input': {'source': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app',
           'target': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode/Applications/Xcode_10.1.app'}}
FileMover: File /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_unpack/Xcode.app moved to /Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode/Applications/Xcode_10.1.app
{'Output': {}}
MunkiInstallsItemsCreator
{'Input': {'faux_root': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode',
           'installs_item_paths': (
    "/Applications/Xcode_10.1.app"
),
           'version_comparison_key': u'CFBundleVersion'}}
MunkiInstallsItemsCreator: Created installs item for /Applications/Xcode_10.1.app
{'Output': {'additional_pkginfo': {'installs': (
        {
        CFBundleIdentifier = "com.apple.dt.Xcode";
        CFBundleName = Xcode;
        CFBundleShortVersionString = "10.1";
        CFBundleVersion = "14460.46";
        minosversion = "10.13.6";
        path = "/Applications/Xcode_10.1.app";
        type = application;
        "version_comparison_key" = CFBundleVersion;
    }
)}}}
MunkiPkginfoMerger
{'Input': {'additional_pkginfo': {'installs': (
        {
        CFBundleIdentifier = "com.apple.dt.Xcode";
        CFBundleName = Xcode;
        CFBundleShortVersionString = "10.1";
        CFBundleVersion = "14460.46";
        minosversion = "10.13.6";
        path = "/Applications/Xcode_10.1.app";
        type = application;
        "version_comparison_key" = CFBundleVersion;
    }
)},
           'pkginfo': {
    catalogs =     (
        testing
    );
    description = Xcode;
    "display_name" = Xcode;
    name = Xcode;
    "unattended_install" = 1;
}}}
MunkiPkginfoMerger: Merged {'installs': (
        {
        CFBundleIdentifier = "com.apple.dt.Xcode";
        CFBundleName = Xcode;
        CFBundleShortVersionString = "10.1";
        CFBundleVersion = "14460.46";
        minosversion = "10.13.6";
        path = "/Applications/Xcode_10.1.app";
        type = application;
        "version_comparison_key" = CFBundleVersion;
    }
)} into pkginfo
{'Output': {'pkginfo': {
    catalogs =     (
        testing
    );
    description = Xcode;
    "display_name" = Xcode;
    installs =     (
                {
            CFBundleIdentifier = "com.apple.dt.Xcode";
            CFBundleName = Xcode;
            CFBundleShortVersionString = "10.1";
            CFBundleVersion = "14460.46";
            minosversion = "10.13.6";
            path = "/Applications/Xcode_10.1.app";
            type = application;
            "version_comparison_key" = CFBundleVersion;
        }
    );
    name = Xcode;
    "unattended_install" = 1;
}}}
com.facebook.autopkg.shared/InstallsArrayFineTuning
{'Input': {'additional_pkginfo': {'installs': (
        {
        CFBundleIdentifier = "com.apple.dt.Xcode";
        CFBundleName = Xcode;
        CFBundleShortVersionString = "10.1";
        CFBundleVersion = "14460.46";
        minosversion = "10.13.6";
        path = "/Applications/Xcode_10.1.app";
        type = application;
        "version_comparison_key" = CFBundleVersion;
    }
)},
           'changes': (
        {
        path = "/Applications/Xcode_10.1.app";
        type = bundle;
    }
)}}
InstallsArrayFineTuning: Replacing type for /Applications/Xcode_10.1.app to bundle
{'Output': {'changed_pkginfo': (
        {
        CFBundleIdentifier = "com.apple.dt.Xcode";
        CFBundleName = Xcode;
        CFBundleShortVersionString = "10.1";
        CFBundleVersion = "14460.46";
        minosversion = "10.13.6";
        path = "/Applications/Xcode_10.1.app";
        type = bundle;
        "version_comparison_key" = CFBundleVersion;
    }
)}}
MunkiPkginfoMerger
{'Input': {'additional_pkginfo': {
    "display_name" = "Xcode 10.1 (10B61)";
    "icon_name" = "Xcode.png";
    name = "Xcode10.1";
    version = "10.1.0.14460.46";
},
           'pkginfo': {
    catalogs =     (
        testing
    );
    description = Xcode;
    "display_name" = Xcode;
    installs =     (
                {
            CFBundleIdentifier = "com.apple.dt.Xcode";
            CFBundleName = Xcode;
            CFBundleShortVersionString = "10.1";
            CFBundleVersion = "14460.46";
            minosversion = "10.13.6";
            path = "/Applications/Xcode_10.1.app";
            type = bundle;
            "version_comparison_key" = CFBundleVersion;
        }
    );
    name = Xcode;
    "unattended_install" = 1;
}}}
MunkiPkginfoMerger: Merged {
    "display_name" = "Xcode 10.1 (10B61)";
    "icon_name" = "Xcode.png";
    name = "Xcode10.1";
    version = "10.1.0.14460.46";
} into pkginfo
{'Output': {'pkginfo': {
    catalogs =     (
        testing
    );
    description = Xcode;
    "display_name" = "Xcode 10.1 (10B61)";
    "icon_name" = "Xcode.png";
    installs =     (
                {
            CFBundleIdentifier = "com.apple.dt.Xcode";
            CFBundleName = Xcode;
            CFBundleShortVersionString = "10.1";
            CFBundleVersion = "14460.46";
            minosversion = "10.13.6";
            path = "/Applications/Xcode_10.1.app";
            type = bundle;
            "version_comparison_key" = CFBundleVersion;
        }
    );
    name = "Xcode10.1";
    "unattended_install" = 1;
    version = "10.1.0.14460.46";
}}}
DmgCreator
{'Input': {'dmg_path': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode_10.1.dmg',
           'dmg_root': u'/Volumes/Repo/Cache/com.facebook.autopkg.xcode.munki/Xcode/Applications'}}
...
```

**Comment by nmcspadden** [comment] 2019-03-19 18:48
I'm closing this because I can't reproduce this, if you can provide more exact data on the problems you're having, or an exact 100% reproducible repro case, we can revisit it.

**Closed by nmcspadden** 2019-03-19 18:48 UTC
