### ISSUE TITLE
Xcode Extract Recipe with 9.2

### ISSUE THREAD

**Issue by clburlison** [facebook/Recipes-for-AutoPkg#17] opened 2018-02-02 13:47 UTC
In its current form the XcodeXip extract processor doesn’t work with 9.2. @pudquick if you could sync the internal changes that would be super swell. 🤗

It looks like Xcode 9 was patched with https://github.com/facebook/Recipes-for-AutoPkg/commit/76e4f98bb88f69d9d23634a96f5ece8038cf1127

but 9.2 keeps giving me the following ditto error
`ditto: cpio read error: bad file format`

**Comment by nmcspadden** [comment] 2018-02-13 15:22
I was unable to reproduce this error. I just tried on both Xcode 9.2 and 9.3 beta 2 xips from Apple.

Xcode 9.3 beta 2:
https://gist.github.com/nmcspadden/6fe5411db3094ab5b81209357d548137

Xcode 9.2:
https://gist.github.com/nmcspadden/2663196fb2de7a0c432ed445294f11f5

**Comment by nmcspadden** [comment] 2018-02-14 20:18
Closing this because I can't repro.

**Closed by nmcspadden** 2018-02-14 20:18 UTC

**Comment by clburlison** [comment] 2018-02-19 17:45
That's interesting. I setup a clean 10.13.3 machine installed the Xcode CLI tools, autopkg install, then a repo-add and still get a ditto error.

https://gist.github.com/clburlison/51a9c232aacafb8816f8ea78a96ce396

Would you mind validating my checksum values against yours?

```bash
vagrant-17D47:~ teamcity$ shasum a256 ~/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Xcode/XcodeXIPUnpacker.py
shasum: a256: 
d7f7d0f78713f8d908a2b62fd88af60da16642b8  /Users/teamcity/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Xcode/XcodeXIPUnpacker.py
vagrant-17D47:~ teamcity$ shasum a256 ~/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Xcode/XcodeVersioner.py
shasum: a256: 
ff02bcbe468dccd8202140c0a81b0a78533abf90  /Users/teamcity/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Xcode/XcodeVersioner.py
vagrant-17D47:~ teamcity$ shasum a256 ~/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Xcode/Xcode.munki.recipe 
shasum: a256: 
6db6c7697ec7344790bb42f79311846107c6473a  /Users/teamcity/Library/AutoPkg/RecipeRepos/com.github.facebook.Recipes-for-AutoPkg/Xcode/Xcode.munki.recipe
```
